import re
import sys
import os

filepath = sys.argv[1] if len(sys.argv) > 1 else 'R3 APP/App.tsx'

with open(filepath, 'r') as f:
    content = f.read()

# 1. Replace Imports
content = re.sub(
    r'// --- Firebase Setup ---.*?const db = firebase\.firestore\(\);',
    r'''import { supabase } from '../src/lib/supabase';\n\nconst auth = supabase.auth;\nconst db = supabase;''',
    content,
    flags=re.DOTALL
)

# 2. Update Auth State Changed
content = re.sub(
    r'const unsubscribe = auth\.onAuthStateChanged\(\(user: any\) => \{([^}]+)\}\);.*?return \(\) => unsubscribe\(\);',
    r'''const { data: { subscription } } = auth.onAuthStateChanged((event, session) => {\n            const user = session?.user || null;\n\1});\n        return () => subscription.unsubscribe();''',
    content,
    flags=re.DOTALL
)

content = re.sub(
    r'auth\.signOut\(\);',
    r'auth.signOut();',
    content
)

# 3. Subscriptions (onSnapshot) -> Initial Fetch + Realtime
# For generic collections
def replace_subscription(match):
    collection = match.group(1) # clients, tasks, revisionHistory, projections
    state_key = match.group(2) # clients, tasks, revisionHistory, savedProjections
    
    table_map = {
        'clients': 'app_clients',
        'tasks': 'app_tasks',
        'revisionHistory': 'app_revisions',
        'projections': 'app_projections'
    }
    table = table_map.get(collection, collection)
    
    return f'''
        const fetch{collection.capitalize()} = async () => {{
            const {{ data, error }} = await db.from('{table}').select('*');
            if (error) {{
                showError("Error al cargar {collection}: " + error.message);
                return;
            }}
            // Adapt data
            const adaptedData = data.map(doc => ({{ ...doc, id: doc.id }}));
            updateAppState({{ {state_key}: adaptedData }});
        }};

        fetch{collection.capitalize()}();

        const channel{collection.capitalize()} = db.channel('public:{table}')
            .on('postgres_changes', {{ event: '*', schema: 'public', table: '{table}' }}, payload => {{
                fetch{collection.capitalize()}(); // simple refetch on any change
            }})
            .subscribe();
'''

content = re.sub(
    r'const \w+Unsubscribe = db\.collection\(\'(\w+)\'\)\s*\.onSnapshot\(\(snapshot: any\) => \{\s*const \w+ = snapshot\.docs\.map\(\(doc: any\) => \(\{\s*\.\.\.doc\.data\(\),\s*id: doc\.id\s*\}\)\);\s*updateAppState\(\{ (\w+): \w+ \}\);\s*\}, \(err: any\) => showError\("[^"]+" \+ err\.message\)\);',
    replace_subscription,
    content
)

# Handle history and projections which have order and where clauses
def replace_history_subscription(match):
    collection = match.group(1)
    state_key = match.group(2)
    
    table = 'app_revisions' if collection == 'revisionHistory' else 'app_projections'
    
    return f'''
        const fetch{collection.capitalize()} = async () => {{
            const {{ data, error }} = await db.from('{table}').select('*').eq('user_id', user.id).order('created_at', {{ ascending: false }});
            if (error) {{
                showError("Error al cargar {collection}: " + error.message);
                return;
            }}
            const adaptedData = data.map(doc => ({{ ...doc, id: doc.id, createdAt: new Date(doc.created_at) }}));
            updateAppState({{ {state_key}: adaptedData }});
        }};

        fetch{collection.capitalize()}();

        const channel{collection.capitalize()} = db.channel('public:{table}')
            .on('postgres_changes', {{ event: '*', schema: 'public', table: '{table}' }}, payload => {{
                fetch{collection.capitalize()}();
            }})
            .subscribe();
'''

content = re.sub(
    r'const \w+Unsubscribe = db\.collection\(\'(\w+)\'\)\s*\.where\(\'userId\', \'==\', user\.uid\)\s*\.orderBy\(\'createdAt\', \'desc\'\)[^;]+?updateAppState\(\{ (\w+): \w+ \}\);\s*\}, \(err: any\) => showError\("[^"]+" \+ err\.message\)\);',
    replace_history_subscription,
    content,
    flags=re.DOTALL
)

# Return cleanup
content = re.sub(
    r'return \(\) => \{\s*clientsUnsubscribe\(\);\s*tasksUnsubscribe\(\);\s*historyUnsubscribe\(\);\s*projectionsUnsubscribe\(\);\s*\};',
    r'''return () => {\n            db.removeChannel(channelClients);\n            db.removeChannel(channelTasks);\n            db.removeChannel(channelRevisionHistory);\n            db.removeChannel(channelProjections);\n        };''',
    content
)


# 4. CRUD Operations
# create task batch sync tasks
content = content.replace(
'''            const tasksQuery = db.collection('tasks')
                .where('clientId', '==', client.id)
                .where('isAutoGenerated', '==', true);
                
            const querySnapshot = await tasksQuery.get();
            const existingTasks = new Map<string, Task>();
            querySnapshot.forEach((doc: any) => {
                existingTasks.set(doc.id, { id: doc.id, ...doc.data() } as Task);
            });

            const batch = db.batch();
            const requiredTaskIds = new Set(requiredTasks.map(t => t.deadlineId));

            for (const task of requiredTasks) {
                if (task.deadlineId) {
                    const taskRef = db.collection('tasks').doc(task.deadlineId);
                    batch.set(taskRef, task);
                }
            }

            for (const existingId of existingTasks.keys()) {
                if (!requiredTaskIds.has(existingId)) {
                    const taskRef = db.collection('tasks').doc(existingId);
                    batch.delete(taskRef);
                }
            }

            await batch.commit();''',
'''            const { data: existingDocs } = await db.from('app_tasks')
                .select('*')
                .eq('client_id', client.id)
                .eq('is_auto_generated', true);
            
            const existingTasks = new Map<string, Task>();
            if (existingDocs) {
                existingDocs.forEach((doc: any) => {
                    existingTasks.set(doc.id, { id: doc.id, ...doc } as Task);
                });
            }

            const requiredTaskIds = new Set(requiredTasks.map(t => t.deadlineId));

            // Upsert required tasks
            for (const task of requiredTasks) {
                if (task.deadlineId) {
                    await db.from('app_tasks').upsert({ id: task.deadlineId, ...task, client_id: client.id, is_auto_generated: true, user_id: user.id });
                }
            }

            // Delete obsolete tasks
            for (const existingId of existingTasks.keys()) {
                if (!requiredTaskIds.has(existingId)) {
                    await db.from('app_tasks').delete().eq('id', existingId);
                }
            }'''
)

# saveClient
content = content.replace(
'''            if (clientId) {
                const { id, userId, ...dataToUpdate } = clientData;
                await db.collection('clients').doc(clientId).update(dataToUpdate);
                const originalClient = appState.clients.find(c => c.id === clientId);
                savedClient = { ...originalClient, ...dataToUpdate, id: clientId } as Client;
            } else {
                const { id, ...dataToCreate } = clientData;
                const docRef = await db.collection('clients').add({ ...dataToCreate, userId: user.uid });
                savedClient = { ...dataToCreate, id: docRef.id, userId: user.uid } as Client;
            }''',
'''            // Adapt to camel case in standard TS object, but save to snake as needed or just save.
            // But wait, the table uses snake_case and UUIDs.
            let savedClient: any;
            if (clientId) {
                const { id, userId, ...dataToUpdate } = clientData;
                const { data, error } = await db.from('app_clients').update(dataToUpdate).eq('id', clientId).select().single();
                if (error) throw error;
                savedClient = data;
            } else {
                const { id, ...dataToCreate } = clientData;
                const { data, error } = await db.from('app_clients').insert({ ...dataToCreate, user_id: user.id }).select().single();
                if (error) throw error;
                savedClient = data;
            }'''
)

# user.uid -> user.id in other places
content = content.replace('user.uid', 'user.id')

# deleteClient
content = content.replace(
'''            const batch = db.batch();
            const clientRef = db.collection('clients').doc(clientId);
            batch.delete(clientRef);

            const tasksQuery = db.collection('tasks').where('clientId', '==', clientId);
            const tasksSnapshot = await tasksQuery.get();
            tasksSnapshot.forEach((doc: any) => {
                batch.delete(doc.ref);
            });

            await batch.commit();''',
'''            await db.from('app_clients').delete().eq('id', clientId);
            await db.from('app_tasks').delete().eq('client_id', clientId);'''
)

# saveTask
content = content.replace(
'''            if (isNew) {
                const { id, userId, ...dataToCreate } = taskToSave;
                await db.collection('tasks').add({ ...dataToCreate, userId: user.uid, isAutoGenerated: false });
            } else {
                const { id, userId, ...dataToUpdate } = taskToSave;
                await db.collection('tasks').doc(taskId).update(dataToUpdate);
            }''',
'''            if (isNew) {
                const { id, userId, ...dataToCreate } = taskToSave;
                const { error } = await db.from('app_tasks').insert({ ...dataToCreate, user_id: user.id, is_auto_generated: false });
                if (error) throw error;
            } else {
                const { id, userId, ...dataToUpdate } = taskToSave;
                const { error } = await db.from('app_tasks').update(dataToUpdate).eq('id', taskId);
                if (error) throw error;
            }'''
)

# deleteTask
content = content.replace(
'''await db.collection('tasks').doc(taskId).delete();''',
'''await db.from('app_tasks').delete().eq('id', taskId);'''
)

# saveRevision serverTimestamp
content = content.replace(
'''firebase.firestore.FieldValue.serverTimestamp()''',
'''new Date().toISOString()'''
)

# field paths
content = content.replace(
'''firebase.firestore.FieldPath.documentId()''',
'''"id"'''
)

# saveRevision add
content = content.replace(
'''await db.collection('revisionHistory').add(revision);''',
'''const { error } = await db.from('app_revisions').insert({ ...revision, user_id: user.id }); if (error) throw error;'''
)

# deleteRevision
content = content.replace(
'''await db.collection('revisionHistory').doc(revisionId).delete();''',
'''await db.from('app_revisions').delete().eq('id', revisionId);'''
)

# saveProyeccion
content = content.replace(
'''await db.collection('projections').add(projectionToSave);''',
'''const { error } = await db.from('app_projections').insert({ ...projectionToSave, user_id: user.id }); if (error) throw error;'''
)

# updateProyeccion
content = content.replace(
'''await db.collection('projections').doc(id).update(cleanData);''',
'''const { error } = await db.from('app_projections').update(cleanData).eq('id', id); if (error) throw error;'''
)

# deleteProyeccion
content = content.replace(
'''await db.collection('projections').doc(proyeccionId).delete();''',
'''await db.from('app_projections').delete().eq('id', proyeccionId);'''
)

with open(filepath, 'w') as f:
    f.write(content)

print("App.tsx refactored")
