import React, { useState, useContext, useMemo } from 'react';
import { AppContext } from '@/dashboard/contexts/AppContext';
import type { Task, TaskStatus } from '@/dashboard/types';
import TaskModal from '@/dashboard/components/TaskModal';
import { EditIcon, DeleteIcon, XMarkIcon, DriveIcon, SearchIcon, BoltIcon } from '@/dashboard/components/Icons';

const statusColors: Record<TaskStatus, { bg: string, text: string, border: string }> = {
    'vencida': { bg: 'bg-red-100', text: 'text-red-800', border: 'border-l-4 border-red-500' },
    'por-presentar': { bg: 'bg-amber-100', text: 'text-amber-800', border: 'border-l-4 border-amber-500' },
    'borrador': { bg: 'bg-orange-100', text: 'text-orange-800', border: 'border-l-4 border-orange-500' },
    'presentado': { bg: 'bg-green-100', text: 'text-green-800', border: 'border-l-4 border-green-500' },
};


const SearchResultTaskItem: React.FC<{
    task: Task;
    onEdit: (task: Task) => void;
    onDelete: (task: Task) => void;
}> = ({ task, onEdit, onDelete }) => {
    const { dueDate, title, status, comments, driveLink } = task;
    const context = useContext(AppContext);
    const colors = statusColors[status];
    const formattedDate = new Date(dueDate + 'T00:00:00').toLocaleDateString('es-CO', { year: 'numeric', month: 'long', day: 'numeric' });
    
    const showStartReviewButton = task.title.includes('Revisión Mensual') || task.title.includes('ReteFuente');
    const handleStartReviewClick = () => {
        if (task.title.includes('Revisión Mensual')) {
            context?.startRevisionFromTask(task);
        } else if (task.title.includes('ReteFuente')) {
            context?.startRetencionesFromTask(task);
        }
    };

    return (
        <div className={`p-3 rounded-md flex justify-between items-start group ${colors.bg} ${colors.border}`}>
            <div className="flex-1 mr-4">
                <div className="flex items-center space-x-2">
                    <p className="font-semibold text-slate-800">{title}</p>
                    {driveLink && (
                        <a href={driveLink} target="_blank" rel="noopener noreferrer" onClick={(e) => e.stopPropagation()} className="p-1 rounded-full hover:bg-black/10" title="Abrir en Google Drive">
                            <DriveIcon className="w-4 h-4" />
                        </a>
                    )}
                </div>
                <p className={`text-sm mt-1 ${status === 'vencida' ? 'text-red-600 font-bold' : 'text-slate-600'}`}>
                    Vence: {formattedDate}
                </p>
                {comments && comments.length > 0 && (
                     <div className="mt-2 text-xs text-slate-500 pl-4 border-l-2 border-slate-200 space-y-1">
                        {comments.map((c, i) => (
                            <p key={i} className="truncate" title={c}>{c}</p>
                        ))}
                    </div>
                )}
            </div>
            <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                {showStartReviewButton && (
                    <button onClick={handleStartReviewClick} className="p-2 rounded-full hover:bg-white/50" title="Iniciar Revisión">
                        <BoltIcon className="w-5 h-5 text-amber-600"/>
                    </button>
                )}
                <button onClick={() => onEdit(task)} className="p-2 rounded-full hover:bg-white/50" title="Editar"><EditIcon className="w-5 h-5"/></button>
                {!task.isAutoGenerated && (
                    <button onClick={() => onDelete(task)} className="p-2 rounded-full hover:bg-white/50" title="Eliminar"><DeleteIcon className="w-5 h-5"/></button>
                )}
            </div>
        </div>
    );
};

const Calendar: React.FC = () => {
    const context = useContext(AppContext);
    const [currentDate, setCurrentDate] = useState(new Date());
    const [isTaskModalOpen, setIsTaskModalOpen] = useState(false);
    const [taskToEdit, setTaskToEdit] = useState<Task | Partial<Task> | null>(null);
    const [dayModal, setDayModal] = useState<{ day: number; tasks: Task[] } | null>(null);
    const [taskToDelete, setTaskToDelete] = useState<Task | null>(null);
    const [searchTerm, setSearchTerm] = useState('');

    if (!context) {
        return <div>Cargando...</div>;
    }

    const { appState, saveTask, deleteTask, startRevisionFromTask, startRetencionesFromTask } = context;
    const { tasks } = appState;

    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();

    const tasksByDay = useMemo(() => {
        const map = new Map<number, Task[]>();
        tasks.forEach(task => {
            const taskDate = new Date(task.dueDate + 'T00:00:00');
            if (taskDate.getFullYear() === year && taskDate.getMonth() === month) {
                const day = taskDate.getDate();
                const dayTasks = map.get(day) || [];
                dayTasks.push(task);
                map.set(day, dayTasks.sort((a,b) => a.title.localeCompare(b.title)));
            }
        });
        return map;
    }, [tasks, year, month]);

    const filteredTasks = useMemo(() => {
        if (searchTerm.length < 3) return [];
        const lowercasedSearch = searchTerm.toLowerCase();
        return tasks.filter(task => 
            task.title.toLowerCase().includes(lowercasedSearch) ||
            (task.clientName && task.clientName.toLowerCase().includes(lowercasedSearch))
        );
    }, [tasks, searchTerm]);
    
    const groupedTasks = useMemo(() => {
        if (filteredTasks.length === 0) return new Map<string, Task[]>();

        const grouped = new Map<string, Task[]>();
        filteredTasks.forEach(task => {
            const key = task.clientName || 'Tareas Generales';
            const collection = grouped.get(key);
            if (!collection) {
                grouped.set(key, [task]);
            } else {
                collection.push(task);
            }
        });

        grouped.forEach(group => group.sort((a,b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime()));

        return grouped;
    }, [filteredTasks]);

    const firstDayOfMonth = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const monthName = currentDate.toLocaleString('es-CO', { month: 'long' });
    const today = new Date();
    const isCurrentMonth = today.getFullYear() === year && today.getMonth() === month;

    const goToPrevMonth = () => setCurrentDate(new Date(year, month - 1, 1));
    const goToNextMonth = () => setCurrentDate(new Date(year, month + 1, 1));
    
    const handleSaveTask = (task: Task) => {
        saveTask(task);
        setIsTaskModalOpen(false);
        setTaskToEdit(null);
        setDayModal(null); // Close day modal if open
    };
    
    const handleCloseModal = () => {
        setIsTaskModalOpen(false);
        setTaskToEdit(null);
    };

    const handleDayClick = (day: number) => {
        const date = new Date(year, month, day);
        const isoDate = date.toISOString().split('T')[0];
        const newTaskTemplate: Partial<Task> = { dueDate: isoDate, status: 'borrador', comments: [''] };
        setTaskToEdit(newTaskTemplate);
        setIsTaskModalOpen(true);
    };

    const handleEditTask = (task: Task) => {
        setTaskToEdit(task);
        setIsTaskModalOpen(true);
    };
    
    const handleDeleteRequest = (task: Task) => {
        setTaskToDelete(task);
    };

    const handleConfirmDelete = () => {
        if (taskToDelete) {
            deleteTask(taskToDelete.id);
            // Also update the dayModal if it's open
            if (dayModal) {
                setDayModal(prev => ({
                    ...prev!,
                    tasks: prev!.tasks.filter(t => t.id !== taskToDelete.id)
                }));
            }
            setTaskToDelete(null);
        }
    };
    
    const handleStartReviewClick = (e: React.MouseEvent, task: Task) => {
        e.stopPropagation();
        if (task.title.includes('Revisión Mensual')) {
            startRevisionFromTask(task);
        } else if (task.title.includes('ReteFuente')) {
            startRetencionesFromTask(task);
        }
    };

    const renderDays = () => {
        const days = [];
        for (let i = 0; i < firstDayOfMonth; i++) {
            days.push(<div key={`empty-${i}`} className="bg-slate-50/50"></div>);
        }
        for (let day = 1; day <= daysInMonth; day++) {
            const dayTasks = tasksByDay.get(day) || [];
            const isToday = isCurrentMonth && day === today.getDate();
            days.push(
                <div key={day} className="bg-white p-2 relative min-h-[130px] flex flex-col group hover:bg-slate-50 transition-colors cursor-pointer" onClick={() => handleDayClick(day)}>
                    <span className={`text-sm font-semibold self-start mb-1 ${isToday ? 'bg-amber-500 text-white rounded-full w-7 h-7 flex items-center justify-center shadow-md drop-shadow-sm' : 'text-slate-700 ml-1'}`}>{day}</span>
                    <div className="mt-1 space-y-1.5 flex-grow">
                        {dayTasks.slice(0, 3).map(task => {
                            const borderClass = statusColors[task.status].border.replace('border-l-4', 'border-l-2');
                            return (
                            <div key={task.id} onClick={(e) => { e.stopPropagation(); handleEditTask(task); }} className={`flex items-center text-xs rounded-md px-2 py-1 opacity-90 transition-all hover:scale-[1.02] hover:opacity-100 cursor-pointer ${statusColors[task.status].bg} ${statusColors[task.status].text} ${borderClass} shadow-sm`} title={task.title}>
                                <span className="truncate flex-1 font-medium">{task.title}</span>
                                {task.driveLink ? (
                                    <a href={task.driveLink} target="_blank" rel="noopener noreferrer" onClick={(e) => e.stopPropagation()} title="Abrir en Google Drive" className="ml-1 p-0.5 rounded-full hover:bg-black/10 flex-shrink-0">
                                        <DriveIcon className="w-3 h-3" />
                                    </a>
                                ) : null}
                            </div>
                        )})}
                        {dayTasks.length > 3 && (
                            <button onClick={(e) => { e.stopPropagation(); setDayModal({ day, tasks: dayTasks }); }} className="text-xs text-blue-600 font-semibold hover:underline w-full text-left mt-1 pl-1">
                                Ver {dayTasks.length - 3} más...
                            </button>
                        )}
                    </div>
                </div>
            );
        }
        return days;
    };
    
    const renderSearchResults = () => {
        if (groupedTasks.size === 0) {
            return <p className="text-center text-slate-500 mt-8">No se encontraron tareas para su búsqueda.</p>;
        }

        return (
            <div className="space-y-6">
                {Array.from(groupedTasks.entries()).map(([clientName, clientTasks]) => (
                    <div key={clientName}>
                        <h3 className="text-xl font-bold text-slate-800 border-b pb-2 mb-3">{clientName}</h3>
                        <div className="space-y-3">
                            {clientTasks.map(task => (
                                <SearchResultTaskItem key={task.id} task={task} onEdit={handleEditTask} onDelete={handleDeleteRequest} />
                            ))}
                        </div>
                    </div>
                ))}
            </div>
        );
    };


    return (
        <>
            <header className="mb-8">
                <h1 className="text-4xl font-bold text-slate-800">Calendario de Vencimientos</h1>
                <p className="text-slate-500 mt-1">Visualice y gestione las tareas de sus clientes.</p>
            </header>
            
            <div className="mb-6 relative">
                <span className="absolute inset-y-0 left-0 flex items-center pl-3">
                    <SearchIcon className="text-slate-400" />
                </span>
                <input
                    type="text"
                    placeholder="Buscar por cliente o título de la tarea (mínimo 3 caracteres)..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="w-full pl-10 pr-10 py-2 bg-white border border-gray-300 text-gray-900 placeholder-gray-500 rounded-lg focus:ring-amber-500 focus:border-amber-500"
                />
                {searchTerm && (
                    <button onClick={() => setSearchTerm('')} className="absolute inset-y-0 right-0 flex items-center pr-3">
                        <XMarkIcon className="w-5 h-5 text-slate-400 hover:text-slate-600" />
                    </button>
                )}
            </div>

            {searchTerm.length < 3 ? (
                <div className="bg-white rounded-lg shadow p-6">
                    <div className="flex justify-between items-center mb-4">
                        <button onClick={goToPrevMonth} className="p-2 rounded-full hover:bg-slate-100">
                            <svg className="h-6 w-6 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" /></svg>
                        </button>
                        <h2 className="text-2xl font-bold text-slate-800 capitalize">{monthName} {year}</h2>
                        <button onClick={goToNextMonth} className="p-2 rounded-full hover:bg-slate-100">
                            <svg className="h-6 w-6 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7" /></svg>
                        </button>
                    </div>

                    <div className="grid grid-cols-7 text-center font-semibold text-slate-600 text-sm pb-3">
                        <div>Do</div><div>Lu</div><div>Ma</div><div>Mi</div><div>Ju</div><div>Vi</div><div>Sá</div>
                    </div>
                    <div className="grid grid-cols-7 gap-[1px] bg-slate-200 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
                        {renderDays()}
                    </div>
                </div>
            ) : (
                <div className="bg-white rounded-lg shadow p-6">
                    {renderSearchResults()}
                </div>
            )}


            {isTaskModalOpen && <TaskModal onClose={handleCloseModal} onSave={handleSaveTask} taskToEdit={taskToEdit as Task | null} />}
            
            {dayModal && (
                <div className="fixed inset-0 bg-slate-900 bg-opacity-60 backdrop-blur-sm flex items-center justify-center z-50 p-4" onClick={() => setDayModal(null)}>
                    <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[80vh] flex flex-col" onClick={e => e.stopPropagation()}>
                        <header className="flex justify-between items-center p-4 border-b">
                            <h3 className="text-xl font-bold text-slate-800">Tareas del {dayModal.day} de {monthName}</h3>
                             <button onClick={() => setDayModal(null)} className="p-1 rounded-full text-slate-500 hover:bg-slate-100"><XMarkIcon/></button>
                        </header>
                        <main className="p-4 overflow-y-auto">
                            <ul className="space-y-3">
                                {dayModal.tasks.map(task => {
                                    const showStartReviewButton = task.title.includes('Revisión Mensual') || task.title.includes('ReteFuente');
                                    return (
                                        <li key={task.id} className={`p-3 rounded-md flex justify-between items-center group ${statusColors[task.status].bg}`}>
                                            <div>
                                                <p className={`font-bold ${statusColors[task.status].text}`}>{task.title}</p>
                                                <p className="text-sm text-slate-600">{task.clientName || 'General'}</p>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                {showStartReviewButton && (
                                                    <button onClick={(e) => handleStartReviewClick(e, task)} className="p-2 rounded-full hover:bg-white/50" title="Iniciar Revisión">
                                                        <BoltIcon className="w-5 h-5 text-amber-600" />
                                                    </button>
                                                )}
                                                {task.driveLink && (
                                                    <a href={task.driveLink} target="_blank" rel="noopener noreferrer" className="p-2 rounded-full hover:bg-white/50" title="Abrir en Google Drive" onClick={(e) => e.stopPropagation()}>
                                                        <DriveIcon className="w-5 h-5" />
                                                    </a>
                                                )}
                                                <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                                    <button onClick={() => handleEditTask(task)} className="p-2 rounded-full hover:bg-white/50" title="Editar"><EditIcon className="w-5 h-5"/></button>
                                                    <button onClick={() => handleDeleteRequest(task)} className="p-2 rounded-full hover:bg-white/50" title="Eliminar"><DeleteIcon className="w-5 h-5"/></button>
                                                </div>
                                            </div>
                                        </li>
                                    );
                                })}
                            </ul>
                        </main>
                    </div>
                </div>
            )}
            
            {taskToDelete && (
                 <div className="fixed inset-0 bg-slate-900 bg-opacity-60 backdrop-blur-sm flex items-center justify-center z-[60]">
                    <div className="bg-white p-6 rounded-lg shadow-xl max-w-sm text-center">
                        <h3 className="text-lg font-bold text-slate-800">Confirmar Eliminación</h3>
                        <p className="my-4 text-slate-600">¿Está seguro que desea eliminar la tarea "{taskToDelete.title}"? Esta acción no se puede deshacer.</p>
                        <div className="flex justify-center gap-4">
                            <button onClick={() => setTaskToDelete(null)} className="px-6 py-2 rounded-lg bg-slate-200 text-slate-800 font-semibold hover:bg-slate-300">Cancelar</button>
                            <button onClick={handleConfirmDelete} className="px-6 py-2 rounded-lg bg-red-600 text-white font-semibold hover:bg-red-700">Eliminar</button>
                        </div>
                    </div>
                </div>
            )}
        </>
    );
};

export default Calendar;