
export type Module = 'dashboard' | 'contable' | 'iva' | 'retenciones' | 'informe' | 'clients' | 'tasks' | 'calendar' | 'historial' | 'proyecciones-iva' | 'proyecciones-portfolio' | 'configuracion';

export type FileType = 'auxiliar' | 'compras' | 'ventas' | 'dian' | 'validacion' | 'retencion_base' | 'iva_auxiliar' | 'iva_dian' | 'retencion_auxiliar' | 'retencion_compras' | 'retencion_ventas';

export type FileStatus = 'pending' | 'loading' | 'success' | 'error';

export interface FileState {
    file: File | null;
    status: FileStatus;
    name: string;
    data: any[] | null;
}

export interface AuxiliarData {
    id: string;
    Cuenta: string;
    Tercero: string;
    NIT: string;
    Fecha: string; // DD/MM/YYYY
    Nota: string;
    DocNum: string;
    Debitos: number;
    Creditos: number;
    isModified?: boolean;
    comentario?: string;
}

export interface RetencionBaseData {
    id: string;
    Codigo: string;
    CuentaDocumento: string;
    Fecha: string;
    Tercero: string;
    Valor: number;
    Porcentaje: number;
    Base: number;
    comentario?: string;
    isModified?: boolean;
}

export interface DianData {
    id: string;
    TipoDeDocumento: string;
    Folio: string;
    Prefijo: string;
    DocumentoDIAN: string; // Prefijo + Folio
    Fecha: string; // DD/MM/YYYY
    FechaObj: Date | null;
    NITEMISOR: string;
    NombreEmisor: string;
    NITReceptor: string;
    NombreReceptor: string;
    IVA: number;
    Base: number;
    Total: number;
    Grupo: string;
    
    // Additional tax fields
    ICA?: number;
    IC?: number;
    INC?: number;
    Timbre?: number;
    INCBolsas?: number;
    INCarbono?: number;
    INCombustibles?: number;
    ICDatos?: number;
    ICL?: number;
    INPP?: number;
    IBUA?: number;
    ICUI?: number;
    ReteIVA?: number;
    ReteRenta?: number;
    ReteICA?: number;
}

export interface VentasComprasData {
    id: string;
    Documento: string;
    Fecha: string;
    FechaObj: Date | null;
    Cliente: string;
    NIT: string;
    VentaNeta: number;
    IVA: number;
    Dias: string;
    Descuento: number;
    RetIVA: number;
    RetICA: number;
    RetFuente: number;
    ValorTotal: number;
}

export interface DocumentoDetalle {
    docNum: string;
    docNumWO: string;
    docNumDIAN: string;
    fecha: string;
    valorWO: number;
    valorDIAN: number;
    diferencia: number;
    tipo: 'coincide' | 'diferenciaValor' | 'faltaDIAN' | 'faltaWO';
}

export interface Diferencia {
    nit: string;
    nombre: string;
    valorWO: number;
    valorDIAN: number;
    diferencia: number;
    observaciones: string;
    detalles?: DocumentoDetalle[];
}

export interface ResumenDiferencias {
    ingresos: Diferencia[];
    ivaGen: Diferencia[];
    compras: Diferencia[];
    ivaDesc: Diferencia[];
}

export interface ConciliacionResultados {
    ingresos: Diferencia[];
    ivaGen: Diferencia[];
    compras: Diferencia[];
    ivaDesc: Diferencia[];
}

export interface AnalisisCuenta {
    cuenta: string;
    nombre: string;
    saldoAuxiliar: number;
    saldoDian: number;
    diferencia: number;
    estado: 'ok' | 'revision' | 'critico';
}

export interface Task {
    id: string;
    title: string;
    clientId: string | null;
    clientName: string | null;
    dueDate: string; // ISO date string YYYY-MM-DD
    status: 'borrador' | 'por-presentar' | 'vencida' | 'presentado';
    comments?: string[];
    isAutoGenerated?: boolean;
    deadlineId?: string; // Unique ID for auto-generated recurring tasks
    driveLink?: string;
    userId?: string;
}

export type TaskStatus = Task['status'];

export interface Ciiu {
    code: string;
    description: string;
}

export interface Client {
    id: string;
    userId?: string;
    tipoPersona: 'Persona Jurídica' | 'Persona Natural';
    
    // Identificación
    razonSocial?: string; // Solo PJ
    nombreCompleto?: string; // Solo PN
    nit?: string; // Solo PJ
    nitDv?: string;
    cedula?: string; // Solo PN
    cedulaDv?: string;

    // Representante Legal (Solo PJ principalmente, pero adaptable)
    representanteLegal?: string;
    cedulaRepLegal?: string;
    cedulaRepLegalDv?: string;

    // Contacto y Ubicación
    direccion: string;
    departamento: string;
    municipio: string;
    emails: string[];
    celulares: string[];
    
    // Clasificación Tributaria
    ciiuCodes: Ciiu[];
    responsabilidadesNacionales: {
        iva: 'bimestral' | 'cuatrimestral' | null;
        consumo: boolean;
        rteFte: boolean;
        renta: boolean;
        exogenas: boolean;
        gmf?: boolean;
        impuestoPatrimonio?: boolean;
        preciosTransferencia?: boolean;
        gasolina?: boolean;
        carbono?: boolean;
        plasticos?: boolean;
        bebidasUltraprocesadas?: boolean;
        cuotasRenta?: {
            cuota1: boolean;
            cuota2: boolean;
            cuota3: boolean;
        };
    };
    responsabilidadesMunicipales: {
        ica: string[]; // Lista de municipios donde paga ICA
    };
    tipoContribuyente: string; // "Gran Contribuyente", "Responsable de IVA", etc.
    otherObligations: {
        revisionMensual: boolean;
    };

    status: 'Activo' | 'Inactivo';
    
    // --- NEW: Account Configuration ---
    knownAccounts?: {
        income: string[];
        purchase: string[];
        iva: string[];
    };
    
    // --- NEW: IVA Classification Config ---
    configuracionIva?: {
        income: Record<string, VatCategory>; // AccountCode -> Category
        purchase: Record<string, VatCategory>; // AccountCode -> Category
        ivaDescontable?: Record<string, IvaDescontableCategory>;
    };

    clavePortal: string;
}

export interface ValidationData {
    nombreValidado: string;
    estado: string;
    dv: string;
}

export interface ValidationResult {
    inactivos: { nit: string; nombreWO: string; data: ValidationData }[];
    noEncontrados: { nit: string; nombreWO: string }[];
    conErrorNombre: { nit: string; nombreWO: string; data: ValidationData }[];
    activos: number;
}

export type TipoHallazgo = 'RETENCION_OMITIDA' | 'RETENCION_INDEBIDA' | 'TARIFA_INCORRECTA' | 'BASE_INCORRECTA' | 'SIGNO_INCORRECTO' | 'COHERENCIA_LOGICA';

export interface RetencionFinding {
    id: string;
    docNum: string;
    proveedor: string;
    nit?: string;
    fecha?: string;
    base: number;
    retencionAplicada: number;
    tipoHallazgo: TipoHallazgo;
    inconsistenciaDetectada: string;
    accionRecomendada: string;
    movimientos: AuxiliarData[];
    
    // Metadata for analysis
    concepto?: string;
    retencionEsperada?: number;

    // User Interaction
    omitted?: boolean;
    omitComment?: string;
}

export type VatCategory = 'gravado' | 'exento' | 'excluido' | 'no_gravado' | 'no_clasificado';
export type CompraVatCategory = 'no_clasificado' | 'bienes_gravados_5' | 'bienes_gravados_g' | 'servicios_gravados_5' | 'servicios_gravados_g' | 'excluidos_exentos_no_gravados';
export type IvaDescontableCategory = 'no_clasificado_descontable' | 'bienes_5' | 'bienes_g' | 'servicios_5' | 'servicios_g' | 'no_tener_en_cuenta';


export interface IvaDocumentDetail {
    docNum: string;
    nota: string;
    valor: number;
    key: string;
}

export interface IvaAccountDetail {
    cuenta: string;
    nombre: string;
    valorAuxiliar: number;
    documentos?: IvaDocumentDetail[];
}

export interface IvaCategoryData {
    accounts: IvaAccountDetail[];
    totalAuxiliar: number;
    totalDian: number;
    totalDianGravado?: number;
    totalDianOtros?: number;
    dianDocuments?: DianDocumentDetail[];
}

export interface DianDocumentDetail {
    docNum: string;
    fecha: string;
    baseGravada: number;
    baseOtros: number;
    total: number;
}


export interface IvaSectionResult {
    gravados: IvaCategoryData;
    devolucionesGravadas: IvaCategoryData;
    
    exentos: IvaCategoryData;
    devolucionesExentas: IvaCategoryData;
    
    excluidos: IvaCategoryData;
    devolucionesExcluidas: IvaCategoryData;
    
    noGravados: IvaCategoryData;
    devolucionesNoGravadas: IvaCategoryData;
}

export interface IvaLiquidationResult {
    ingresos: IvaSectionResult;
    compras: IvaSectionResult;
    resumen: {
        ivaGenerado: number;
        ivaDescontable: number;
        saldoAPagar: number;
    };
}

export interface DocumentoDiscrepancia {
    docNum: string;
    nit: string;
    nombre: string;
    fecha: string;
    valorWo: number;
    valorDian: number;
    diferencia: number;
    observacion?: string;
    tipo?: 'FALTANTE_DIAN' | 'FALTANTE_WO' | 'DIFERENCIA_VALOR';
}

export interface DocumentoDiscrepanciaClasificacion {
    docNum: string;
    nit: string;
    nombre: string;
    fecha: string;
    baseGravadaWo: number;
    baseNoGravadaWo: number;
    baseGravadaDian: number;
    baseNoGravadaDian: number;
    diferenciaGravado: number;
    diferenciaNoGravado: number;
    diferenciaTotal: number;
    observacion: 'Reclasificado' | 'Diferencia Valor' | 'Faltante en DIAN' | 'Faltante en WO';
}


export interface GroupedDiscrepancy {
    nit: string;
    nombre: string;
    totalValorWo: number;
    totalValorDian: number;
    totalDiferencia: number;
    detalles: DocumentoDiscrepancia[];
}

export interface IvaRevisionResult {
    ingresos: {
        faltantesEnDian: DocumentoDiscrepancia[];
        faltantesEnWo: DocumentoDiscrepancia[];
        conDiferenciaValor: DocumentoDiscrepancia[];
    };
    ingresosClasificacion: DocumentoDiscrepanciaClasificacion[];
    ivaGenerado: {
        faltantesEnDian: DocumentoDiscrepancia[];
        faltantesEnWo: DocumentoDiscrepancia[];
        conDiferenciaValor: DocumentoDiscrepancia[];
    };
    compras: {
        faltantesEnDian: DocumentoDiscrepancia[];
        faltantesEnWo: DocumentoDiscrepancia[];
        conDiferenciaValor: DocumentoDiscrepancia[];
    };
    ivaDescontable: {
        faltantesEnDian: DocumentoDiscrepancia[];
        faltantesEnWo: DocumentoDiscrepancia[];
        conDiferenciaValor: DocumentoDiscrepancia[];
    };
}

export interface CoherenciaFinding {
    id: string;
    docNum: string;
    fecha: string;
    tercero: string;
    inconsistencia: string;
    accionSugerida: string;
    movimientos: AuxiliarData[];
    lineasInconsistentes: number[]; // Indices of rows with issues
    totalDebitos?: number;
    totalCreditos?: number;
    diferencia?: number;
}

export interface RevisionHistoryItem {
    id: string;
    userId: string;
    revisionName: string;
    clientName: string;
    periodo: string;
    createdAt: Date;
    results: {
        conciliacionResultados: ConciliacionResultados | null;
        resumenDiferencias: ResumenDiferencias | null;
        analisisCuentas: AnalisisCuenta[] | null;
        validationResult: ValidationResult | null;
        retencionesResult: RetencionFinding[] | null;
        ivaRevisionResult: IvaRevisionResult | null;
        coherenciaContableResult: CoherenciaFinding[] | null;
        
        // --- IVA DATA ---
        ivaLiquidationResult: IvaLiquidationResult | null;
        ivaState?: {
            incomeAccountVatClassification: Record<string, VatCategory>;
            purchaseAccountVatClassification: Record<string, CompraVatCategory>;
            ivaTransactionVatOverrides: Record<string, VatCategory>;
            ivaDescontableClassification?: Record<string, IvaDescontableCategory>;
            comprasAccountVatClassification?: Record<string, CompraVatCategory>;
            ivaIncomeComments?: Record<string, string>;
        }
    };
}

export interface MonthlySnapshot {
    periodLabel: string;
    monthIndex: number;
    isProjected: boolean;
    timestamp: number;
    
    ivaGenerado: number;
    ivaDescontable: number;
    reteIva: number;
    
    ingresosBrutos: number;
    comprasBrutas: number;
}

export interface SavedProyeccion {
    id: string;
    userId: string;
    clientName: string;
    periodo: string; // e.g., "Enero - Febrero"
    createdAt: any;
    
    // Core Data
    status: 'En Curso' | 'Cerrado';
    history: MonthlySnapshot[];
    
    // Config
    parametros: {
        saldoFavorAnterior: number;
        ajusteIngresosPct: number;
        ajusteComprasPct: number;
        coeficienteProrrateo: number;
    };
    
    // Target
    metaDefinida: number;

    // Legacy (Optional for backward compat)
    snapshotMes1?: any;
    resultadoCalculado?: any;
}


// Union type for generic finding usage
export type AnyFinding = Diferencia | RetencionFinding | CoherenciaFinding | DocumentoDiscrepancia | DocumentoDiscrepanciaClasificacion;

export interface ComparisonResult {
    corregidos: { categoria: string; hallazgo: AnyFinding }[];
    nuevos: { categoria: string; hallazgo: AnyFinding }[];
    modificados: { categoria: string; hallazgoAntes: AnyFinding; hallazgoDespues: AnyFinding }[];
    identicos: { categoria: string; hallazgo: AnyFinding }[];
}

export interface TransactionDetail {
    id: string;
    cuenta: string;
    tercero: string;
    nit: string;
    docNum: string;
    base: number;
    valor: number;
    porcentaje: number;
    concepto: string;
}

export interface ConceptSummary {
    base: number;
    retencion: number;
    transactions: TransactionDetail[];
}

export interface ClassificationData {
    [concept: string]: ConceptSummary;
}

export interface LiquidacionSummary {
    pj: ClassificationData;
    pn: ClassificationData;
    reteIva: number;
    exonerados: {
        base_aux: number;
        retencion_contab: number;
        tarifa_promedio: number;
        base_ing: number;
        retencion_ing_calc: number;
        diferencia_ret: number;
    };
}

export interface LiquidationCalculations {
    ivaGeneradoVentas: number;
    devolucionesComprasProrrateadas: number;
    devolucionesVentas: number;
    ivaDescontableFinal: number;
    ivaTransitorioFinal: number;
    retencionIva: number;
    ivaAPagarReal: number;
    ivaCalculado19: number;
    totalIvaGeneradoBrutoBp: number;
    totalIvaDevolucionesVentasBp: number;
    ivaVentasDian: number;
    ivaDevolucionesVentasDian: number;
    totalIvaDescontableBp: number;
    totalIvaTransitorioBp: number;
    totalIvaDevolucionesComprasBp: number;
    ivaComprasDian: number;
    ivaDevolucionesComprasDian: number;
}

export interface AppState {
    razonSocial: string;
    periodo: string;
    tipoPeriodo: string;
    files: {
        auxiliar: AuxiliarData[] | null;
        compras: VentasComprasData[] | null;
        ventas: VentasComprasData[] | null;
        dian: DianData[] | null;
        validacion: Map<string, ValidationData> | null;
        retencion_base: RetencionBaseData[] | null;
        iva_auxiliar: AuxiliarData[] | null;
        iva_dian: DianData[] | null;
        retencion_auxiliar: AuxiliarData[] | null;
        retencion_compras: VentasComprasData[] | null;
        retencion_ventas: VentasComprasData[] | null;
    };
    fileUploadStatus: {
        [key in FileType]: { status: FileStatus; name: string };
    };
    allNits: Map<string, string>;
    conciliacionResultados: ConciliacionResultados | null;
    analisisCuentas: AnalisisCuenta[] | null;
    resumenDiferencias: ResumenDiferencias | null;
    validationResult: ValidationResult | null;
    retencionesResult: RetencionFinding[] | null;
    liquidacionSummary: LiquidacionSummary | null;
    liquidacionTarifaIng: number;
    liquidacionAutorretencionSource: 'contable' | 'calculada';
    conceptOverrides: Map<string, string>;
    transactionConceptOverrides: Map<string, string>;
    needsRegeneration: boolean;

    // IVA Specific State
    incomeAccountVatClassification: Map<string, VatCategory>;
    purchaseAccountVatClassification: Map<string, VatCategory>;
    ivaTransactionVatOverrides: Map<string, VatCategory>;
    ivaNeedsRecalculation: boolean;
    retencionesNeedsRecalculation: boolean;
    ivaLiquidationResult: IvaLiquidationResult | null;
    comprasAccountVatClassification: Map<string, CompraVatCategory>;
    ivaIncomeComments: Map<string, string>;
    ivaDescontableClassification: Map<string, IvaDescontableCategory>;
    ivaPeriodo: string;
    ivaTipoPeriodo: string;
    ivaRevisionResult: IvaRevisionResult | null;
    coherenciaContableResult: CoherenciaFinding[] | null;
    
    clients: Client[];
    tasks: Task[];
    revisionHistory: RevisionHistoryItem[];
    savedProjections: SavedProyeccion[];
}

export interface LoadingState {
    isActive: boolean;
    message: string;
}

export interface AppContextType {
    appState: AppState;
    updateAppState: (newState: Partial<AppState>) => void;
    setActiveModule: (module: Module) => void;
    startRevisionFromTask: (task: Task) => void;
    startRetencionesFromTask: (task: Task) => void;
    saveClient: (client: Partial<Client>) => void;
    deleteClient: (clientId: string) => void;
    saveTask: (task: Task) => void;
    deleteTask: (taskId: string) => void;
    saveRevision: () => void;
    deleteRevision: (revisionId: string) => void;
    saveProyeccion: (proyeccionData: Omit<SavedProyeccion, 'id' | 'userId' | 'createdAt'>) => void;
    updateProyeccion: (id: string, data: Partial<SavedProyeccion>) => Promise<void>;
    deleteProyeccion: (proyeccionId: string) => void;
    showLoading: (message: string) => void;
    hideLoading: () => void;
    showError: (message: string) => void;
    hideError: () => void;
    showNotification: (message: string) => void;
    hideNotification: () => void;
    onExportExcel?: () => void;
}